export const MOBILE_BREAKPOINT = 480;
export const TABLET_BREAKPOINT = 768;
export const DESKTOP_BREAKPOINT = 1440;

export default [ MOBILE_BREAKPOINT, TABLET_BREAKPOINT, DESKTOP_BREAKPOINT ].map((x) => `${x}px`);
